name: Upload To Azure Blob Storage
on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Publish locations
        uses: Azure/cli@v1.0.0
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload --file $GITHUB_WORKSPACE/posadas/data/*.json --connection-string ${{ secrets.ConnectionString }} --name posadastrallard --container-name ${{secrets.container}}
